name: lamar_finetune
channels:
  - pytorch
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pyyaml
  - regex
  - flash-attn
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - pip:
      - transformers==4.37.0
      - datasets==2.16.1
      - accelerate==0.26.1
      - evaluate==0.4.1
      - safetensors
      - sentencepiece
      - Bio
      - h5py
